kind: pipeline
name: default

image_pull_secrets:
  - dockerconfig

steps:
  - name: build-started
    image: plugins/slack
    settings:
      webhook:
        from_secret: slackurl
      channel: builds
      username: drone
      icon_url: https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/microsoft/153/rocket_1f680.png
      template: >
        {{#success build.status}}
          {{uppercasefirst repo.name}} build {{build.number}} started:  {{build.link}}
          Commit: ${DRONE_COMMIT_LINK}
        {{else}}
          {{uppercasefirst repo.name}} build {{build.number}} failed: {{build.link}}
        {{/success}}
    when:
      status:
        - success
        - failure
      branch:
        - master
      event:
        - push
        - tag

  - name: deploy
    image: quay.io/torreycommerce/scalr_deploy:latest
    environment:
      SCALR_URL:
        from_secret: scalr_url
      SCALR_API_KEY:
        from_secret: scalr_api_key
      SCALR_API_SECRET:
        from_secret: scalr_api_secret
      DEPLOY_PATH: "/var/www/themes/mia"
      REPOSITORY: "git@github.com:torreycommerce/mia.git"
      BRANCH: "master"
    commands:
      - ruby /usr/src/app/scalr.rb
    when:
      event:
        - push
        - tag
      branch:
        - master

  - name: build-finished
    image: plugins/slack
    settings:
      webhook:
        from_secret: slackurl
      channel: builds
      username: drone
      template: >
        {{#success build.status}}
          {{uppercasefirst repo.name}} build {{build.number}} succeeded after {{since build.started}}: {{build.link}}
        {{else}}
          {{uppercasefirst repo.name}} build {{build.number}} failed after {{since build.started}}: {{build.link}}
        {{/success}}
    when:
      status:
        - success
        - failure
      branch:
        - master
      event:
        - push
        - tag
