.common: &common
  user: acenda
  http_user: www-data
  identityFile: ~/.ssh/id_rsa
  sshOptions:
    UserKnownHostsFile: /dev/null
    StrictHostKeyChecking: no
  deploy_path: /var/www/mia_deploy

# Web-servers
172.30.0.59:
  <<: *common
  stage: production
  roles:
    -  app
172.30.0.78:
  <<: *common
  stage: production
  roles:
    - app
172.30.0.79:
  <<: *common
  stage: production
  roles:
    - app
